SistemaVentasWeb/Controllers/ReporteController.cs
/*
* NombreClase: ReporteController.cs
* Autores: Maria Alejandra Pabon - 1310263
* Fecha: 12/Junio/2015
* Descripcion: clase encargada de generar los reportes de ventas
*/

/*
* ActionResult Index()
 * ActionResult VentasPorProducto()
 * ActionResult VentasPorProducto(DateTime fecha_inicio, DateTime fecha_fin)
 * ActionResult ReporteProducto(string id, DateTime fechai, DateTime fechaf)
 * ActionResult VentasPorCategoria()
 * ActionResult VentasPorCategoria(DateTime fecha_inicio, DateTime fecha_fin)
 * ActionResult ReporteCategoria(string id, DateTime fechai, DateTime fechaf)
 * ActionResult VentasPorCiudad()
 * ActionResult VentasPorCiudad(DateTime fecha_inicio, DateTime fecha_fin)
 * ActionResult ReporteCiudad(string id, DateTime fechai, DateTime fechaf)
 * ActionResult VentasPorDiaSemana()
 * ActionResult VentasPorDiaSemana(DateTime fecha_inicio, DateTime fecha_fin)
 * ActionResult ReporteDiaSemana(string id, DateTime fechai, DateTime fechaf)

*/
using Microsoft.Reporting.WebForms;
using SistemaVentasBL;
using SistemaVentasEntidades;
using SistemaVentasWeb.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace SistemaVentasWeb.Controllers
{
    public class ReporteController : Controller
    {

        BL bl = new BL();


        /*
          *Propósito: Controla el inicio de los reportes
          *Entradas: void
          *Salidas: ActionResult
          */
        //#Metodo: Index
        // GET: Reporte
        [Authorize(Roles = "Area de Ventas, Administrador")]
        public ActionResult Index()
        {                
            return View();
        }

        /*
        *Propósito: Genera la lista de ventas por producto
        *Entradas: void
        *Salidas: ActionResult
        */
        //#Metodo:VentasPorProducto 
        [Authorize(Roles = "Area de Ventas, Administrador")]
        public ActionResult VentasPorProducto()
        {
            List<ReporteProducto> pedidos = new List<ReporteProducto>();
            return View(pedidos);
        }


        /*
       *Propósito: Genera la lista de ventas por producto
       *Entradas: DateTime fecha_inicio, DateTime fecha_fin
       *Salidas: ActionResult
       */
        //#Metodo: VentasPorProducto  
         [Authorize(Roles = "Area de Ventas, Administrador")]
        [HttpPost]
        public ActionResult VentasPorProducto(DateTime fecha_inicio, DateTime fecha_fin)
        {
           
               
                List<ReporteProducto> pedidos = new List<ReporteProducto>();
                ReporteProducto pedidoTemporal;
            try
             {
                 List<string> pedidosProducto = bl.consultarCantidadPedidoPorProducto(fecha_inicio, fecha_fin);
                for (int i = 0; i < pedidosProducto.Count() - 1; i += 3)
                {
                    pedidoTemporal = new ReporteProducto();
                    pedidoTemporal.FechaInicio = fecha_inicio;
                    ViewBag.desde = "desde";
                    ViewBag.hasta = "hasta";
                    ViewBag.fechainicio = fecha_inicio.ToString("yyyy-MM-dd");
                    pedidoTemporal.FechaFin = fecha_fin;
                    ViewBag.fechafin = fecha_fin.ToString("yyyy-MM-dd");
                    pedidoTemporal.Codigo = pedidosProducto.ElementAt(i);
                    pedidoTemporal.Producto = pedidosProducto.ElementAt(i + 1);
                    pedidoTemporal.Cantidad = pedidosProducto.ElementAt(i + 2);
                    pedidos.Add(pedidoTemporal);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Seleccione las fechas para generar el reporte");
            }

            return View(pedidos);
            
          
        }


        /*
      *Propósito: Genera el reporte de ventas por producto
      *Entradas: DateTime fecha_inicio, DateTime fecha_fin
      *Salidas: ActionResult
      */
        //#Metodo: ReporteProducto  
         [Authorize(Roles = "Area de Ventas, Administrador")]
        public ActionResult ReporteProducto(string id, DateTime fechai, DateTime fechaf)
        {
            LocalReport lr = new LocalReport();
            string path = Path.Combine(Server.MapPath("~/Reportes"), "VentasPorProducto.rdlc");
            if (System.IO.File.Exists(path))
            {
                lr.ReportPath = path;
            }
            else
            {
                return View("Index");
            }


            List<string> pedidosProducto = bl.consultarCantidadPedidoPorProducto(fechai, fechaf);
            List<ReporteProducto> pedidos = new List<ReporteProducto>();
            ReporteProducto pedidoTemporal;

            for (int i = 0; i < pedidosProducto.Count() - 1; i += 3)
            {
                pedidoTemporal = new ReporteProducto();
                pedidoTemporal.FechaInicio = fechai.Date;
                pedidoTemporal.FechaFin = fechaf.Date;    
                pedidoTemporal.Codigo = pedidosProducto.ElementAt(i);
                pedidoTemporal.Producto = pedidosProducto.ElementAt(i + 1);
                pedidoTemporal.Cantidad = pedidosProducto.ElementAt(i + 2);
                pedidos.Add(pedidoTemporal);
            }


            ReportDataSource rd = new ReportDataSource("VentasPorProductoDataSet", pedidos);
            lr.DataSources.Add(rd);
            string reportType = id;
            string mimeType;
            string encoding;
            string fileNameExtension;



            string deviceInfo =
            "<DeviceInfo>" +
            "  <OutputFormat>" + id + "</OutputFormat>" +
            "  <PageWidth>8.5in</PageWidth>" +
            "  <PageHeight>11in</PageHeight>" +
            "  <MarginTop>0.5in</MarginTop>" +
            "  <MarginLeft>1in</MarginLeft>" +
            "  <MarginRight>1in</MarginRight>" +
            "  <MarginBottom>0.5in</MarginBottom>" +
            "</DeviceInfo>";

            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;

            renderedBytes = lr.Render(
                reportType,
                deviceInfo,
                out mimeType,
                out encoding,
                out fileNameExtension,
                out streams,
                out warnings);



            return File(renderedBytes, mimeType);
        }


        /*
        *Propósito: Genera la lista de ventas por producto
        *Entradas: void
        *Salidas: ActionResult
        */
        //#Metodo:VentasPorCategoria
         [Authorize(Roles = "Area de Ventas, Administrador")]
        public ActionResult VentasPorCategoria()
        {
            List<ReporteCategoria> pedidos = new List<ReporteCategoria>();
            return View(pedidos);
        }


        /*
      *Propósito: Genera la lista de ventas por categoria
      *Entradas: DateTime fecha_inicio, DateTime fecha_fin
      *Salidas: ActionResult
      */
        //#Metodo: VentasPorCategoria 
         [Authorize(Roles = "Area de Ventas, Administrador")]
        [HttpPost]
        public ActionResult VentasPorCategoria(DateTime fecha_inicio, DateTime fecha_fin)
        {
            
            List<ReporteCategoria> pedidos = new List<ReporteCategoria>();
            ReporteCategoria pedidoTemporal;

            try
            {
                List<string> pedidosCategoria = bl.consultarCantidadPedidoPorCategoria(fecha_inicio, fecha_fin);
                for (int i = 0; i < pedidosCategoria.Count() - 1; i += 3)
                {
                    pedidoTemporal = new ReporteCategoria();
                    pedidoTemporal.FechaInicio = fecha_inicio;
                    ViewBag.desde = "desde";
                    ViewBag.hasta = "hasta";
                    ViewBag.fechainicio = fecha_inicio.ToString("yyyy-MM-dd");
                    pedidoTemporal.FechaFin = fecha_fin;
                    ViewBag.fechafin = fecha_fin.ToString("yyyy-MM-dd");
                    pedidoTemporal.Codigo = pedidosCategoria.ElementAt(i);
                    pedidoTemporal.Categoria = pedidosCategoria.ElementAt(i + 1);
                    pedidoTemporal.Cantidad = pedidosCategoria.ElementAt(i + 2);
                    pedidos.Add(pedidoTemporal);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Seleccione las fechas para generar el reporte");
            }

            
            return View(pedidos);


        }

        /*
        *Propósito: Genera el reporte de ventas por categoria
        *Entradas: DateTime fecha_inicio, DateTime fecha_fin
        *Salidas: ActionResult
        */
        //#Metodo: ReporteCategoria  
         [Authorize(Roles = "Area de Ventas, Administrador")]
        public ActionResult ReporteCategoria(string id, DateTime fechai, DateTime fechaf)
        {
            LocalReport lr = new LocalReport();
            string path = Path.Combine(Server.MapPath("~/Reportes"), "VentasPorCategoria.rdlc");
            if (System.IO.File.Exists(path))
            {
                lr.ReportPath = path;
            }
            else
            {
                return View("Index");
            }


            List<string> pedidosCategoria = bl.consultarCantidadPedidoPorCategoria(fechai, fechaf);
            List<ReporteCategoria> pedidos = new List<ReporteCategoria>();
            ReporteCategoria pedidoTemporal;

            for (int i = 0; i < pedidosCategoria.Count() - 1; i += 3)
            {
                pedidoTemporal = new ReporteCategoria();
                pedidoTemporal.FechaInicio = fechai.Date;
                pedidoTemporal.FechaFin = fechaf.Date;    
                pedidoTemporal.Codigo = pedidosCategoria.ElementAt(i);
                pedidoTemporal.Categoria = pedidosCategoria.ElementAt(i + 1);

SistemaVentasWeb/Views/Reporte/Index.cshtml
@{
    ViewBag.Title = "Reportes";
}


<div class="row">
    <h2>Reportes</h2>
    


    <p class="lead"> Seleccione el reporte que desea generar:     </p>
    <div class="col-md-4">

        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Ventas por producto", "VentasPorProducto", "Reporte")</li>
            <li>@Html.ActionLink("Ventas por categoria de productos", "VentasPorCategoria", "Reporte")</li>
            <li>@Html.ActionLink("Ventas por ciudad", "VentasPorCiudad", "Reporte")</li>
          
            
        </ul>

    </div>
</div>

SistemaVentasWeb/Views/Reporte/VentasPorCategoria.cshtml
@model IList<SistemaVentasWeb.Models.ReporteCategoria>

@{
    ViewBag.Title = "Ventas por categoria de productos";
}

<h2>Ventas por categoria de productos @ViewBag.desde @ViewBag.fechainicio @ViewBag.hasta @ViewBag.fechafin</h2>
<br /><br /><br />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@using (Html.BeginForm())
{

    <table style="margin: 0 auto;">
        <tr>
            <td>Desde </td>
            <td><input type="date" id="fecha_inicio" name="fecha_inicio"></td>


        </tr>
        <tr>
            <td>Hasta</td>
            <td><input type="date" id="fecha_fin" name="fecha_fin"></td>
        </tr>

    </table>
    <p></p>
    <p></p>
    <br />
    <input type="submit" style="Position:relative; left:45%; top:50%"  value="Ver ventas" class="btn btn-default" />


}


        <p></p>
        <p></p>
<br/>


        <table class="table">
            <tr>
                <th>
                    Codigo
                </th>
                <th>
                    Categoria de producto
                </th>
                <th>
                    Cantidad
                </th>
            </tr>


            @for (var i = 0; i < Model.Count; i++)
    {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem[i].Codigo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem[i].Categoria)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem[i].Cantidad)
                    </td>

                </tr>
    }
        </table>

       <p></p>
        <p></p>
        <table>

            <tr>
                
                <td>
                    <div><a href="@Url.Action("ReporteCategoria", new { id = "PDF", fechai = @ViewBag.fechainicio, fechaf = @ViewBag.fechafin })"><img src="~/ImagenesInterfaz/pdf.png" title="Exportar en pdf" /></a></div>
                </td>
                <td>
                    <div><a href="@Url.Action("ReporteCategoria", new { id = "Excel", fechai = @ViewBag.fechainicio, fechaf = @ViewBag.fechafin })"><img src="~/ImagenesInterfaz/excel.png" title="Exportar en excel" /></a></div>
                </td>
            </tr>
            <tr>
                Cuando descargue el PDF debe dar clic derecho en "Guardar Como", escribir el nombre del archivo y la extension .pdf.
            </tr>
        </table>

        <p></p>
        <div>
            @Html.ActionLink("Regresar", "Index", "Reporte")
        </div>

SistemaVentasWeb/Views/Reporte/VentasPorCiudad.cshtml
@model IList<SistemaVentasWeb.Models.ReporteCiudad>

@{
    ViewBag.Title = "Ventas por ciudad";
}

<h2>Ventas por ciudad @ViewBag.desde @ViewBag.fechainicio @ViewBag.hasta @ViewBag.fechafin</h2>
<br /><br /><br />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@using (Html.BeginForm())
{
    <table style="margin: 0 auto;">
        <tr>
            <td>Desde </td>
            <td><input type="date" id="fecha_inicio" name="fecha_inicio"></td>


        </tr>
        <tr>
            <td>Hasta</td>
            <td><input type="date" id="fecha_fin" name="fecha_fin"></td>
        </tr>

    </table>
    <p></p>
    <p></p>
    <br />
    <input type="submit" style="Position:relative; left:45%; top:50%" value="Ver ventas" class="btn btn-default" />



}


<p></p>
<p></p>
<br />

<table class="table">
    <tr>
        <th>
            Ciudad
        </th>
        <th>
            Cantidad
        </th>
    </tr>


    @for (var i = 0; i < Model.Count; i++)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].Ciudad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].Cantidad)
            </td>

        </tr>
    }
</table>

<p></p>
<p></p>
<table>

<tr> <td>
    <div><a href="@Url.Action("ReporteCiudad", new { id = "PDF", fechai = @ViewBag.fechainicio, fechaf = @ViewBag.fechafin })"><img src="~/ImagenesInterfaz/pdf.png" title="Exportar en pdf" /></a></div>
    </td>
    <td>
    <div><a href="@Url.Action("ReporteCiudad", new { id = "Excel", fechai = @ViewBag.fechainicio, fechaf = @ViewBag.fechafin })"><img src="~/ImagenesInterfaz/excel.png" title="Exportar en excel" /></a></div>
    </td>
</tr>
    <tr>
        Cuando descargue el PDF debe dar clic derecho en "Guardar Como", escribir el nombre del archivo y la extension .pdf.
    </tr>
    </table>

<p></p>
    <div>
        @Html.ActionLink("Regresar", "Index", "Reporte")
    </div>

SistemaVentasWeb/Views/Reporte/VentasPorDiaSemana.cshtml
@model IList<SistemaVentasWeb.Models.ReporteDiaSemana>

@{
    ViewBag.Title = "Ventas por dia de la semana";
}

<h2>Ventas por dia de la semana @ViewBag.desde @ViewBag.fechainicio @ViewBag.hasta @ViewBag.fechafin</h2>
<br /><br /><br />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@using (Html.BeginForm())
{
    <table style="margin: 0 auto;">
        <tr>
            <td>Desde </td>
            <td><input type="date" id="fecha_inicio" name="fecha_inicio"></td>


        </tr>
        <tr>
            <td>Hasta</td>
            <td><input type="date" id="fecha_fin" name="fecha_fin"></td>
        </tr>

    </table>
    <p></p>
    <p></p>
    <br />
    <input type="submit" style="Position:relative; left:45%; top:50%" value="Ver ventas" class="btn btn-default" />



}


<p></p>
<p></p>
<br />

<table class="table">
    <tr>
        <th>
            Dia
        </th>
        <th>
            Cantidad
        </th>
    </tr>


    @for (var i = 0; i < Model.Count; i++)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].Dia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].Cantidad)
            </td>

        </tr>
    }
</table>

<p></p>
<p></p>
<table>

    <tr>
        <td>
            <div><a href="@Url.Action("ReporteDiaSemana", new { id = "PDF", fechai = @ViewBag.fechainicio, fechaf = @ViewBag.fechafin })"><img src="~/ImagenesInterfaz/pdf.png" title="Exportar en pdf" /></a></div>
        </td>
        <td>
            <div><a href="@Url.Action("ReporteDiaSemana", new { id = "Excel", fechai = @ViewBag.fechainicio, fechaf = @ViewBag.fechafin })"><img src="~/ImagenesInterfaz/excel.png" title="Exportar en excel" /></a></div>
        </td>
    </tr>
    <tr>
        Cuando descargue el PDF debe dar clic derecho en "Guardar Como", escribir el nombre del archivo y la extension .pdf.
    </tr>
</table>

<p></p>
<div>
    @Html.ActionLink("Regresar", "Index", "Reporte")
</div>

SistemaVentasWeb/Views/Reporte/VentasPorProducto.cshtml
@model IList<SistemaVentasWeb.Models.ReporteProducto>

@{
    ViewBag.Title = "Ventas por categoria de productos";
}

<h2>Ventas por producto @ViewBag.desde @ViewBag.fechainicio @ViewBag.hasta @ViewBag.fechafin</h2>
<br /><br /><br />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@using (Html.BeginForm())
{
    <table style="margin: 0 auto;">
        <tr>
            <td>Desde </td>
            <td><input type="date" id="fecha_inicio" name="fecha_inicio"></td>


        </tr>
        <tr>
            <td>Hasta</td>
            <td><input type="date" id="fecha_fin" name="fecha_fin"></td>
        </tr>

    </table>
    <p></p>
    <p></p>
    <br />

    <input type="submit" style="Position:relative; left:45%; top:50%" value="Ver ventas" class="btn btn-default" />



}


<p></p>
<p></p>
<br />

<table class="table">
    <tr>
        <th>
            Codigo
        </th>
        <th>
            Producto
        </th>
        <th>
            Cantidad
        </th>
    </tr>


    @for (var i = 0; i < Model.Count; i++)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].Producto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].Cantidad)
            </td>

        </tr>
    }
</table>

<p></p>
<p></p>
<table>

    <tr>
        <td>
            <div><a href="@Url.Action("ReporteProducto", new { id = "PDF", fechai = @ViewBag.fechainicio, fechaf = @ViewBag.fechafin })"><img src="~/ImagenesInterfaz/pdf.png" title="Exportar en pdf" /></a></div>
        </td>
        <td>
            <div><a href="@Url.Action("ReporteProducto", new { id = "Excel", fechai = @ViewBag.fechainicio, fechaf = @ViewBag.fechafin })"><img src="~/ImagenesInterfaz/excel.png" title="Exportar en excel" /></a></div>
        </td>
    </tr>
    <tr>
        Cuando descargue el PDF debe dar clic derecho en "Guardar Como", escribir el nombre del archivo y la extension .pdf.
    </tr>
</table>

<p></p>
<div>
    @Html.ActionLink("Regresar", "Index", "Reporte")
</div>