SistemaVentasWeb/Controllers/PerfilController.cs
/*
* NombreClase: PerfilController
* Autores: Edwin Gamboa -1310233
* Fecha: 15/Jun/2015
* Descripcion: Clase que permite controlar las vistas asociadas a la gestión de perfiles.
*/

/*
* ActionResult Index(string searchString)
* ActionResult Create()
* ActionResult Create([Bind(Include = "CodPerfil,Nombre")] PerfilEntidad perfil)
* ActionResult Edit(int id)
* ActionResult Edit([Bind(Include = "CodPerfil,Nombre")] PerfilEntidad perfil)
*/
using SistemaVentasBL;
using SistemaVentasEntidades;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaVentasWeb.Controllers
{
    public class PerfilController : Controller
    {
        BL bl = new BL();

        /*
         *Propósito: Permite listar los perfiles
         *Entradas: string
         *Salidas: ActionResult
         */
        //#Metodo: Index
        // GET: Perfil
        [Authorize(Roles = "Administrador")]
        public ActionResult Index(string searchString)
        {
            ObservableCollection<PerfilEntidad> perfiles;
            if (!String.IsNullOrEmpty(searchString))
            {
                perfiles = bl.consultarPerfilPorNombre(searchString);
            }
            else
            {
                perfiles = bl.consultarTodosLosPerfiles();
            }
            return View(perfiles);
        }

        /*
         *Propósito: Permite crear perfiles
         *Entradas:  
         *Salidas: ActionResult
         */
        //#Metodo: Create
        // GET: Perfil/Create
         [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            return View();
        }

        /*
         *Propósito: Permite crear perfiles
         *Entradas: PerfilEntidad
         *Salidas: ActionResult
         */
        //#Metodo: Create
        // POST: Perfil/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Create([Bind(Include = "CodPerfil,Nombre")]
            PerfilEntidad perfil)
        {
            if (ModelState.IsValid)
            {
                bl.crearPerfil(perfil);                
                return RedirectToAction("Index");
            }

            return View(perfil);
        }


        /*
         *Propósito: Permite editar perfiles
         *Entradas:  int
         *Salidas: ActionResult
         */
        //#Metodo: Edit
        // GET: Perfil/Edit/5
         [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int id)
        {
            PerfilEntidad perfil = bl.consultarPerfilPorCodigo(id);
            return View(perfil);
        }

        /*
         *Propósito: Permite editar perfiles
         *Entradas:  PerfilEntidad
         *Salidas: ActionResult
         */
        //#Metodo: Edit
        // POST: Perfil/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit([Bind(Include = "CodPerfil,Nombre")]
            PerfilEntidad perfil)
        {
            if (ModelState.IsValid)
            {
                bl.editarPerfil(perfil);
                return RedirectToAction("Index");
            }
            return View(perfil);
        }
        
    }
}

SistemaVentasWeb/Views/Perfil/Create.cshtml
@model SistemaVentasEntidades.PerfilEntidad

@{
    ViewBag.Title = "Create";
}

<h2>Crear Perfil</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

SistemaVentasWeb/Views/Perfil/Edit.cshtml
@model SistemaVentasEntidades.PerfilEntidad

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CodPerfil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodPerfil, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.CodPerfil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

SistemaVentasWeb/Views/Perfil/Index.cshtml
@model IEnumerable<SistemaVentasEntidades.PerfilEntidad>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Nuevo Perfil", "Create")
    @using (Html.BeginForm("Index", "Perfil", FormMethod.Get))
    {
    <p>
        Nombre: @Html.TextBox("SearchString")
        <input type="submit" value="Filtrar" />
    </p>
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CodPerfil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CodPerfil)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.CodPerfil })
        </td>
    </tr>
}

</table>